languages: python
python:
  - "3.8"

services:
  - postgresql

install:
  - pip install -r backend/requirements.txt

before_script:
  - psql -c 'create database test_db;' -U postgres

script:
  - make all
