"""add rewards table

Revision ID: 894a59016283
Revises: 68138927fc88
Create Date: 2022-07-11 20:25:25.196858-07:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "894a59016283"
down_revision = "68138927fc88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reward",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("discount", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum("GROCERY", "ENTERTAINMENT", "GAS", "TRAVEL", "EDUCATION", "RESTAURANT", name="rewardtype"),
            nullable=False,
        ),
        sa.Column("valid_from", sa.DateTime(), nullable=False),
        sa.Column("valid_to", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["card.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reward_id"), "reward", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reward_id"), table_name="reward")
    op.drop_table("reward")
    # ### end Alembic commands ###
